name: Deploy

on:
  push:
    branches: [master]

jobs:
  prod-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: openssl?
      run: which openssl
    - name: symlink ssl?
      run: ln -s $(which openssl) /usr/local/opt/openssl@1.1/bin/openssl
    - name: Setup ENV variables in Dockerfile
      run: ./add_variables_to_dockerfile.sh
      env:
        ENV_SECRET: ${{ secrets.ENV_SECRET }}
    - name: Push to registry
      uses: elgohr/Publish-Docker-Github-Action@2.6
      if: github.ref == 'refs/heads/master'
      with:
          name: energetic-wavelength-4450/airflow:ci-${{ github.sha }}
          username: _
          password: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          registry: registry.gcp0001.us-east4.astronomer.io
