name: CI
on:
  push:
    branches: [master]
jobs:
  prod-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push to registry
      uses: elgohr/Publish-Docker-Github-Action@2.6
      if: github.ref == 'refs/heads/master'
      with:
          name: apollos-shovel/airflow:ci-${{ github.sha }}
          username: _
          password: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          registry: registry.gcp0001.us-east4.astronomer.io
